### ISSUE TITLE
s3mysqldump cannot be pip installed without already having boto

### ISSUE THREAD

**Issue by ny2ko** [YelpArchive/s3mysqldump#4]
Some tracebacks:

```
s3mysqldump-0.1 2 ny2ko$ python2.6 setup.py install
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import s3mysqldump
  File "/Users/ny2ko/Downloads/s3mysqldump-0.1 2/s3mysqldump.py", line 36, in <module>
    import boto
ImportError: No module named boto
s3mysqldump-0.1 2 ny2ko$ python2.7 setup.py install
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import s3mysqldump
  File "/Users/ny2ko/Downloads/s3mysqldump-0.1 2/s3mysqldump.py", line 36, in <module>
    import boto
ImportError: No module named boto
```

I think the culprit is in setup.py importing s3mysqldump

**Comment by sudarshang** [comment]
Fixed by 
https://github.com/Yelp/s3mysqldump/commit/54e5255e60de6a6f940c20086bdf54d985b7b294
